"""Build an isolated trial from the existing v4 artifact; never edits official assets.

Run with Isaac Sim Python and the sibling investigation's scripts/env.sh.
v4 was generated under 5.1, not newly generated by the 6.0 importer.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import shutil
import subprocess
import xml.etree.ElementTree as ET

import numpy as np
from pxr import Gf, PhysxSchema, Usd, UsdGeom, UsdPhysics

from static_audit import load_urdf, quaternion_rotation

HERE = Path(__file__).resolve().parents[1]
REPO = HERE.parent
PRIOR = REPO.parent / "sg2_usd_investigation"


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--collider", choices=["capsule", "cylinder", "convex"], default="cylinder")
    parser.add_argument("--promote", action="store_true", help="Copy this explicit candidate to FFW_SG2_trial.usd after validation")
    args = parser.parse_args()
    source = PRIOR / "regen/v4/FFW_SG2_v2.usd"
    urdf = PRIOR / "ai_worker/ffw_description/urdf/ffw_sg2_rev1_follower/ffw_sg2_follower.urdf"
    original = REPO / "source/cyclo_lab/data/robots/FFW/FFW_SG2.usd"
    cfg = REPO / "source/cyclo_lab/cyclo_lab/assets/robots/FFW_SG2.py"
    baseline_path = HERE / "results/baseline.json"
    if not baseline_path.exists():
        baseline_path.write_text(json.dumps({
            "head": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO, text=True).strip(),
            "git_status_before": subprocess.check_output(["git", "status", "--short"], cwd=REPO, text=True),
            "official_sha256": {str(p.relative_to(REPO)): sha(p) for p in (original, cfg)},
            "prior_v4_sha256": sha(source), "urdf_sha256": sha(urdf),
            "isaac_sim_version": Path("/home/robotis/isaacsim/VERSION").read_text().strip(),
        }, indent=2) + "\n")
    shutil.copy2(source, HERE / "runtime/FFW_SG2_v4_source.usd")
    target = HERE / f"runtime/FFW_SG2_{args.collider}.usd"
    shutil.copy2(source, target)
    stage = Usd.Stage.Open(str(target))
    root = stage.GetDefaultPrim()
    # Use the URDF's shared admissible range, rather than importer's expanded mimic limits.
    urdf_root = ET.parse(urdf).getroot()
    # Match the full inertial tensor, not only its three eigenvalues. v4 omitted
    # base_link's off-diagonal tensor terms and left lidar's explicit CoM.
    inertials = load_urdf(urdf)["links"]
    grippers = [j for j in urdf_root.findall("joint") if j.get("name", "").startswith("gripper_") and j.find("limit") is not None]
    lower = max(float(j.find("limit").get("lower")) for j in grippers)
    upper = min(float(j.find("limit").get("upper")) for j in grippers)
    changes = []
    for p in stage.Traverse():
        row = inertials.get(p.GetName())
        if p.HasAPI(UsdPhysics.MassAPI) and row and row["has_inertial"]:
            tensor = row["inertia_link_kg_m2"]
            values, vectors = np.linalg.eigh(tensor)
            assert np.all(values > 0), p.GetPath()
            if np.linalg.det(vectors) < 0:
                vectors[:, 0] *= -1
            # Gf matrix rotations use row vectors; our eigenbasis uses columns.
            quat = Gf.Matrix3d(*vectors.T.ravel()).ExtractRotation().GetQuat()
            axes = Gf.Quatf(float(quat.GetReal()), Gf.Vec3f(*quat.GetImaginary()))
            reconstructed = quaternion_rotation(axes) @ np.diag(values) @ quaternion_rotation(axes).T
            assert np.allclose(reconstructed, tensor, atol=2e-7, rtol=2e-6), p.GetPath()
            mass = UsdPhysics.MassAPI(p)
            before = {"mass": mass.GetMassAttr().Get(), "com": list(mass.GetCenterOfMassAttr().Get()),
                      "diagonal": list(mass.GetDiagonalInertiaAttr().Get())}
            if not np.isfinite(before["com"]).all():
                before["com"] = "USD unspecified CoM sentinel (-inf,-inf,-inf)"
            mass.CreateMassAttr(row["mass_kg"])
            mass.CreateCenterOfMassAttr(Gf.Vec3f(*row["com_link_m"]))
            mass.CreateDiagonalInertiaAttr(Gf.Vec3f(*values))
            mass.CreatePrincipalAxesAttr(axes)
            changes.append({"prim": str(p.GetPath()), "mass_properties_from_pinned_urdf": True,
                            "before": before, "com_m": row["com_link_m"].tolist(),
                            "inertia_tensor_kg_m2": tensor.tolist()})
    for p in stage.Traverse():
        if p.GetName().startswith("gripper_") and p.IsA(UsdPhysics.RevoluteJoint):
            joint = UsdPhysics.RevoluteJoint(p)
            old = [joint.GetLowerLimitAttr().Get(), joint.GetUpperLimitAttr().Get()]
            joint.CreateLowerLimitAttr(math.degrees(lower))
            joint.CreateUpperLimitAttr(math.degrees(upper))
            changes.append({"prim": str(p.GetPath()), "old_limits_deg": old, "trial_limits_rad": [lower, upper]})
    # v4's importer authored CollisionAPI on Xforms. USD Physics ignores these
    # as unknown GPrim types, so body/finger meshes had no effective colliders.
    # Apply the same approximation and flags to the actual Mesh descendants.
    invalid = [p for p in Usd.PrimRange(root, Usd.TraverseInstanceProxies())
               if p.HasAPI(UsdPhysics.CollisionAPI) and not p.IsA(UsdGeom.Gprim)]
    invalid_paths = [p.GetPath() for p in invalid]
    for path in invalid_paths:
        q=stage.GetPrimAtPath(path)
        while q.IsInstanceProxy():
            q=q.GetParent()
        q.SetInstanceable(False)
    for path in invalid_paths:
        parent=stage.GetPrimAtPath(path)
        enabled=UsdPhysics.CollisionAPI(parent).GetCollisionEnabledAttr().Get()
        approx=UsdPhysics.MeshCollisionAPI(parent).GetApproximationAttr().Get()
        meshes=[p for p in Usd.PrimRange(parent) if p.IsA(UsdGeom.Mesh)]
        assert meshes, path
        for mesh in meshes:
            UsdPhysics.CollisionAPI.Apply(mesh).CreateCollisionEnabledAttr(enabled)
            UsdPhysics.MeshCollisionAPI.Apply(mesh).CreateApproximationAttr(approx)
            for attr in parent.GetAttributes():
                if attr.HasAuthoredValueOpinion() and attr.GetName().startswith("physxCollision:"):
                    PhysxSchema.PhysxCollisionAPI.Apply(mesh)
                    mesh.CreateAttribute(attr.GetName(), attr.GetTypeName()).Set(attr.Get())
            changes.append({"collision_api_moved_from_xform": str(path), "actual_mesh": str(mesh.GetPath()),
                            "enabled": enabled, "approximation": approx})
        parent.RemoveAPI(UsdPhysics.CollisionAPI)
        parent.RemoveAPI(UsdPhysics.MeshCollisionAPI)
    # Capsules add 2*r to the wheel width. A finite convex tire preserves URDF width.
    # This is a numerical collision approximation (64 sides), not a measured tire model.
    if args.collider != "capsule":
        wheels = [p for p in Usd.PrimRange(root, Usd.TraverseInstanceProxies())
                  if p.IsA(UsdGeom.Capsule) and "/collisions/" in str(p.GetPath())]
        paths = [p.GetPath() for p in wheels]
        for p in wheels:
            q = p
            while q.IsInstanceProxy():
                q = q.GetParent()
            q.SetInstanceable(False)
        for path in paths:
            p = stage.GetPrimAtPath(path)
            cap = UsdGeom.Capsule(p)
            r, h = cap.GetRadiusAttr().Get(), cap.GetHeightAttr().Get()
            assert cap.GetAxisAttr().Get() == "Z"
            if args.collider == "cylinder":
                geom = UsdGeom.Cylinder.Define(stage, path.GetParentPath().AppendChild("trial_cylinder"))
                geom.CreateAxisAttr("Z")
                geom.CreateRadiusAttr(r)
                geom.CreateHeightAttr(h)
            else:
                geom = UsdGeom.Mesh.Define(stage, path.GetParentPath().AppendChild("trial_tire"))
                n = 64
                points = [(r*math.cos(2*math.pi*i/n), r*math.sin(2*math.pi*i/n), z)
                          for z in (-h/2, h/2) for i in range(n)]
                faces = [[i, (i+1)%n, n+(i+1)%n, n+i] for i in range(n)]
                faces += [list(range(n))[::-1], list(range(n, 2*n))]
                geom.CreatePointsAttr(points)
                geom.CreateFaceVertexCountsAttr([len(f) for f in faces])
                geom.CreateFaceVertexIndicesAttr([i for f in faces for i in f])
                UsdPhysics.MeshCollisionAPI.Apply(geom.GetPrim()).CreateApproximationAttr("convexHull")
            geom.AddTransformOp().Set(cap.GetLocalTransformation())
            UsdPhysics.CollisionAPI.Apply(geom.GetPrim()).CreateCollisionEnabledAttr(True)
            geom.CreatePurposeAttr("guide")
            p.GetAttribute("physics:collisionEnabled").Set(False)
            changes.append({"prim": str(path), "replacement": str(geom.GetPath()), "radius_m": r, "width_m": h})
    stage.GetRootLayer().Save()
    if args.promote:
        shutil.copy2(target, HERE / "runtime/FFW_SG2_trial.usd")
    (HERE / f"results/build_{args.collider}.json").write_text(json.dumps({
        "source_v4": str(source), "source_sha256": sha(source), "trial": str(target),
        "trial_sha256": sha(target), "collider": args.collider, "changes": changes,
        "note": "Isolated reuse of prior 5.1 v4; no 6.0 regeneration or official edits. Motor gains are experimental.",
    }, indent=2)+"\n")
    print(json.dumps({"trial": str(target), "changes": len(changes)}))


if __name__ == "__main__":
    main()
